- name: Wordpress with Docker
  hosts: aws-wordpress
  become: yes

  tasks:
  - name: update repo list
    apt:
      update_cache: yes

  - name: install docker repo dependecies
    apt:
      name:
      - ca-certificates
      - curl
      - gnupg
      - apt-transport-https
      - software-properties-common

  - name: add docker gpg key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

  - name: Add docker to local repo
    apt_repository:
      repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg ] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
      state: present
      update_cache: yes

  - name: Install docker
    apt:
      name: docker-ce
      state: present
      allow_unauthenticated: yes

  - name: Start Docker Service
    systemd:
      name: docker
      enabled: yes
      state: started

  - name: download docker-compose install script
    get_url:
      url: "https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64"
      dest: /usr/local/bin/docker-compose
      mode: 'a+x'
  
  - name: sending docker-compose wordpress file to remote server
    copy:
      src: .
      dest: /home/ubuntu/

  - name: Executing docker-compose up
    ansible.builtin.command:
      cmd: docker-compose -f /home/ubuntu/docker-compose.yml up -d
