version: '3.7'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: senhaqualquer #edite e coloque sua senha
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: senhaqualquer #edite e coloque sua senha
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: senhaqualquer #edite e coloque sua senha
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data:

